#!/usr/bin/env bash
# Configure Nginx to listen on port 80

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen\s*80;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
