#!/usr/bin/env bash
# This Script loops from 1 to 10 and displays:
# "bad luck" for the 4th loop iteration
# "good luck" for the 8th loop iteration
# "Best School" for the other iterations

i="0"

while [ $i -lt 10 ]; do
    i=$((i+1))
    if [ "$i" == 4 ]; then
	echo "bad luck"
    elif [ "$i" == 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
done
