#!/usr/bin/env bash
# This script displays from 1 to 20 and then for:
# 4th loop iteration displays "bad luck from China"
# 9th loop iteration displays "bad luck from Japan"
# 17th loop iteration displays "bad luck from Italy"

i="0"

while [ $i -lt 20 ]; do
    i=$((i+1))
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
done
