#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

h="0"
min="1"

while [ $h -lt 13 ]; do
    echo "Hour: "$h
    h=$((h+1))
    while [ $min -lt 60 ]; do
	echo $min
	min=$((min+1))
    done
    min="1"
done
