#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

for content in *; do
    if [[ -d "$content" || -f "$content" ]]; then
	echo "${content#*-}"
    fi
done
