#!/usr/bin/env bash
# This script configures an Ubuntu server with some requirements

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com " >> /etc/hosts
systemctl restart systemd-resolved.service
