#!/usr/bin/env bash
# Modify Nginx configuration to run as nginx user and listen on port 8080
chmod ugo+wrx  /etc/nginx/nginx.conf
sudo service apache2 stop
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
