#!/usr/bin/env bash
# Modify Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
